name: Deploy RDS PostgreSQL via Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      TF_VAR_db_name: ${{ vars.TF_VAR_DB_NAME }}
      TF_VAR_db_user: ${{ vars.TF_VAR_DB_USER }}
      TF_VAR_db_password: ${{ vars.TF_VAR_DB_PASSWORD }}
      TF_VAR_vpc_id: ${{ vars.TF_VAR_VPC_ID }}
      TF_VAR_subnet_ids: ${{ vars.TF_VAR_SUBNET_IDS }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Inicializar Terraform com backend S3
        run: terraform init -backend-config="bucket=terraform-pipeline-bucket-361598269712" \
          -backend-config="key=rds/terraform.tfstate" \
          -backend-config="region=us-east-1" \
          -backend-config="encrypt=true"

      - name: Validar configuração
        run: terraform validate

      - name: Aplicar infraestrutura
        run: terraform apply -auto-approve
